# Site settings
title: Parsa Riazi Bakhshayesh
description: An Artificial Intelligence enthusiast !
logo: /assets/profile_photo.jpeg
theme: jekyll-theme-minimal # choose a Jekyll theme for your portfolio
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
show_downloads: false # set to true to enable downloads for your projects
